### PR TITLE
Porting all tutorials to OpenTK 4.x

### PR DESCRIPTION
**Pull request by inputusernamehere**
The purpose of this pullrequest is to update all of the LearnOpenTK tutorials to 4.0.

Although all tutorials (except for the GLControl example) now run on OpenTK 4.0, there are still a number of things that need to be ironed out before this is ready to be merged.

0. The GL.LoadBindings() issue. I Left a TODO comment on this in every project.

1. What do we do with the GLControl example? Leave it as is (OpenTK 3.x)?

2. There is a bug with IsFocused in 4.0. It starts out as false even though the window is in fact focused.

3. FrameEventArgs.Time is different in 4.0, so camera movement needs to be calculated differently. I left a TODO comment for this in chapter 1, project 7.

4. It's possible for you to move your mouse, and have OnMouseMove trigger which resets the mouse back to the center of the screen, before OnUpdateFrame triggers and moves the camera.

5. I think an explanation of how OnUpdateFrame and OnRenderFrame's FrameEventArgs.Time works is needed. Why do both of these events contain DeltaTime information, and what makes up a "frame" in OpenTK? I think I understand it now but it was a bit unclear.

6. Updating OpenTK.Net to correspond to these changes.

### CODE REVIEW

**Comment by inputusernamehere** [comment]
Hm, come to think of it, it might be better to have both 3.x and 4.x versions of the tutorial in this repo? If we keep the 3.x tutorials we don't necessarily have to wait for a non-preview release, or for all the points I mentioned to be ironed out.

**Comment by frederikja163** [comment]
> Hm, come to think of it, it might be better to have both 3.x and 4.x versions of the tutorial in this repo? If we keep the 3.x tutorials we don't necessarily have to wait for a non-preview release, or for all the points I mentioned to be ironed out.

**Comment by frederikja163** [comment]
fck, didnt mean to close. Also didnt see your respone. While i do agree that we should keep the 3.x version atleast for quite a while we definitely need to have the things ironed out before we can talk of any merge. What is the status on this. Did you put it down or is it still in progress?

**Comment by inputusernamehere** [comment]
Yeah I put this on hold while a lot of things were still changing in 4.0. I'll have another crack at it.

**Comment by inputusernamehere** [comment]
Points 0-4 are now fixed.

I fixed 1 by simply deleting the GL Control example for now. As far as I understand it's not relevant in 4.x.

I'll open an issue for point 6 in the opentk.net repository.

**Comment by inputusernamehere** [comment]
Point 5 has been fixed as well. This should be more or less ready now. The only thing that remains is to update to a proper release of 4.0!

**Comment by GianLorenzetto** [comment]
Just a +1 to having this merged :) The last couple of days I've been running through the learning docs and having to make these changes myself (at least until I stumbled across this PR).

Thanks for all the work!

**Comment by GianLorenzetto** [comment]
If I could also make a suggestion - the doc uses ImageSharp, but the example is relying on System.Drawing.Common. The latter has some issues on various linux flavours and macOS, relating to the use of libgdiplus. I think that switching the examples to using ImageSharp (and updating the doc, which is a little behind the latest ImageSharp API) would be easier for beginners. I'm happy to put up a PR, once this PR is merged.

Also, is the doc in a separate repo? I'd be happy to contribute some updates, but I can't seem to find it.

**Comment by NogginBops** [comment]
@GianLorenzetto 
> Also, is the doc in a separate repo? I'd be happy to contribute some updates, but I can't seem to find it.

Sorry for the late answer.
Here is the repo that contains the website
https://github.com/opentk/opentk.net

**Comment by NogginBops** [comment]
This branch has been used as the de facto opentk 4.0 tutorial for a while now.
Even if there might be things that could be improved on in this PR we can just make them in followup PRs.

That said, I'm merging this.

**Pull request merged**
