### PR TITLE
Add punctation + Rephrase some comments

### PR DESCRIPTION
**Pull request by Paphos**
Hi there!

I added some punctation where it was needed, fixed some typo, and rephrase some comments that were not very clear.
It is likely that I may have added new mistakes, as English is not my first language! 😅 So let me know if you see one! 😊

I also fixed the color calculation in the "4-Shader-Uniforms" tutorial: the green color was oscillating between -0.5f and 0.5f, instead of 0f and 1f.

And thank you everyone for these awesome tutorials! As someone coming from the MonoGame/XNA world, it really helped me to get truly into OpenGL!! 🥳

### CODE REVIEW

**Comment by deccer** [comment]
I understand punctuation in full sentences, explanations and <summary> regions, but not in simple comments like "// Add a handle for the EBO." If you remove punctation from those then this is alright.

**Comment by Paphos** [comment]
Oh right, I see what you mean. Fixed!

**Comment by Paphos** [comment]
I also fixed the issue #41 at the same time 😊 The PR is ready to be merged on my side! I will maybe do the same for Chapter-2 in another PR if I find some time. 😅

**Review by deccer — APPROVED** [review]
Looks alright to me.

**Pull request merged**
