### PR TITLE
Add first two subchapters

### PR DESCRIPTION
**Pull request by realvictorprm**

### CODE REVIEW

**Comment by frederikja163** [comment]
Remember to also add the .md versions to the website repo

**Comment by realvictorprm** [comment]
yeah need to figure out where I can do that, it's not in this repo.

**Comment by deccer** [comment]
@realvictorprm I did change the folder/project names in the C# variant of this solution, because spaces in folder/project names are not ideal, on linux especially causing a lot of noise in the cli.

Would you be so kind to adopt those changes to your PR, unless you want me to, if you are too busy.

**Comment by frederikja163** [comment]
Im happy to reopen this when you find time @realvictorprm f# tutorials would be awesome to have!

**Pull request closed without merging**
